// Global OOH media companies (structure owners / operators).
// NOT creative agencies — these are the corporations that own and operate
// the physical advertising infrastructure: billboards, digital screens,
// bus shelters, transit displays, airport panels.
// Sourced from ooh.earth/media-corps and industry research.
// HQ coordinates used for the Media Corps world map.

export const OOH_MEDIA_CORPS = [
  {
    name: 'JCDecaux',
    hq: 'Plaisir, France',
    lat: 48.8242,
    lng: 2.0137,
    regions: ['Europe', 'North America', 'Asia-Pacific', 'Latin America', 'Middle East', 'Africa'],
    scope: 'global',
    countries: 80,
    panels: 1000000,
    desc: "World's largest outdoor advertising company. Street furniture, transport, and billboard advertising across 80+ countries.",
    parent: 'JCDecaux SA (family-controlled)',
    url: 'https://www.jcdecaux.com',
    image_url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb09?w=800',
  },
  {
    name: 'Clear Channel Outdoor',
    hq: 'San Antonio, Texas, USA',
    lat: 29.4241,
    lng: -98.4936,
    regions: ['North America', 'Latin America', 'Europe', 'Asia-Pacific'],
    scope: 'global',
    countries: 45,
    panels: 450000,
    desc: 'One of the largest billboard and digital display networks. Operates in US, Latin America, Europe, and Singapore.',
    parent: 'Clear Channel Outdoor Holdings, Inc. (NYSE: CCO)',
    url: 'https://clearchanneloutdoor.com',
    image_url: 'https://images.unsplash.com/photo-1535086181678-5a5c4d23aff7?w=800',
  },
  {
    name: 'Lamar Advertising',
    hq: 'Baton Rouge, Louisiana, USA',
    lat: 30.4515,
    lng: -91.1546,
    regions: ['North America'],
    scope: 'regional',
    countries: 2,
    panels: 352000,
    desc: 'One of the largest outdoor advertising companies in North America. Billboards, digital displays, and transit advertising across US and Canada.',
    parent: 'Lamar Advertising Company (NASDAQ: LAMR)',
    url: 'https://www.lamar.com',
    image_url: 'https://images.unsplash.com/photo-1563861826100-9c8e8cc1b14a?w=800',
  },
  {
    name: 'OUTFRONT Media',
    hq: 'New York, USA',
    lat: 40.7589,
    lng: -73.9851,
    regions: ['North America'],
    scope: 'regional',
    countries: 1,
    panels: 510000,
    desc: 'Billboard, transit, and digital OOH across major US markets. Operates subway, bus shelter, and roadside displays.',
    parent: 'OUTFRONT Media Inc. (NYSE: OUT)',
    url: 'https://www.outfront.com',
    image_url: 'https://images.unsplash.com/photo-1567446537708-ac4aa75c1c12?w=800',
  },
  {
    name: 'Ströer',
    hq: 'Cologne, Germany',
    lat: 50.9375,
    lng: 6.9603,
    regions: ['Europe'],
    scope: 'regional',
    countries: 12,
    panels: 280000,
    desc: 'Leading German OOH and digital media company. Operates billboards, street furniture, and transit across Germany and neighboring European markets.',
    parent: 'Ströer SE & Co. KGaA',
    url: 'https://www.stroeer.com',
    image_url: 'https://images.unsplash.com/photo-1517059224940-d4af9eec41b8?w=800',
  },
  {
    name: 'oOh!media',
    hq: 'Sydney, Australia',
    lat: -33.8688,
    lng: 151.2093,
    regions: ['Asia-Pacific'],
    scope: 'regional',
    countries: 2,
    panels: 37000,
    desc: 'Leading OOH media company in Australia and New Zealand. Roadside, retail, office, and transit formats.',
    parent: 'oOh!media Limited (ASX: OML)',
    url: 'https://www.oohmedia.com.au',
    image_url: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800',
  },
  {
    name: 'Ocean Outdoor',
    hq: 'London, UK',
    lat: 51.5074,
    lng: -0.1278,
    regions: ['Europe'],
    scope: 'regional',
    countries: 1,
    panels: 800,
    desc: 'Premium digital OOH in the UK. Large-format digital screens in high-footfall urban locations.',
    parent: 'Ocean Outdoor Limited',
    url: 'https://oceanoutdoor.com',
    image_url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
  },
  {
    name: 'Global (Exterion Media)',
    hq: 'London, UK',
    lat: 51.5145,
    lng: -0.0755,
    regions: ['Europe'],
    scope: 'regional',
    countries: 5,
    panels: 250000,
    desc: "UK's leading outdoor media company. Airports, roadside posters, premium digital screens. Largest bus advertising provider in the UK.",
    parent: 'Global Group',
    url: 'https://global.com/outdoor/',
    image_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800',
  },
  {
    name: 'Plan B Media',
    hq: 'Bangkok, Thailand',
    lat: 13.7563,
    lng: 100.5018,
    regions: ['Asia-Pacific', 'North America'],
    scope: 'regional',
    countries: 5,
    panels: 12000,
    desc: 'Leading ASEAN OOH media company. Transit media, static and digital billboards across Thailand, Malaysia, Laos, Singapore, and New York.',
    parent: 'Plan B Media PCL (SET: PLANB)',
    url: 'https://www.planbmedia.co.th',
    image_url: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800',
  },
  {
    name: 'Focus Media',
    hq: 'Shanghai, China',
    lat: 31.2304,
    lng: 121.4737,
    regions: ['Asia-Pacific'],
    scope: 'regional',
    countries: 3,
    panels: 2000000,
    desc: "China's largest OOH advertising network. Office building, elevator, and digital screen displays across China and Southeast Asia.",
    parent: 'Focus Media Information Technology Co.',
    url: 'https://www.focusmedia.cn',
    image_url: 'https://images.unsplash.com/photo-1545893835-abaa50cbe628?w=800',
  },
  {
    name: 'Pattison Outdoor',
    hq: 'Toronto, Canada',
    lat: 43.6532,
    lng: -79.3832,
    regions: ['North America'],
    scope: 'regional',
    countries: 1,
    panels: 20000,
    desc: "Canada's largest OOH network. Billboards, transit, and digital screens with deep local market penetration.",
    parent: 'Pattison Outdoor Advertising (Jim Pattison Group)',
    url: 'https://pattisonoutdoor.com',
    image_url: 'https://images.unsplash.com/photo-1517090504534-9a2c8f7c5b5e?w=800',
  },
  {
    name: 'Adams Outdoor Advertising',
    hq: 'Chicago, Illinois, USA',
    lat: 41.8781,
    lng: -87.6298,
    regions: ['North America'],
    scope: 'local',
    countries: 1,
    panels: 6000,
    desc: 'US outdoor advertising operator with billboard and digital billboard inventory across regional US markets.',
    parent: 'Adams Outdoor Advertising',
    url: 'https://www.adamsooh.com',
    image_url: 'https://images.unsplash.com/photo-1572276596237-5db2c3e16c5d?w=800',
  },
  {
    name: 'Build Hollywood',
    hq: 'London, UK',
    lat: 51.5112,
    lng: -0.1205,
    regions: ['Europe'],
    scope: 'local',
    countries: 1,
    panels: 500,
    desc: 'UK large-format OOH specialist. Painted murals, giant posters, and hoardings in urban development sites.',
    parent: 'Build Hollywood Ltd',
    url: 'https://www.buildhollywood.co.uk',
    image_url: 'https://images.unsplash.com/photo-1574169208507-84376144848b?w=800',
  },
  {
    name: 'APG SGA',
    hq: 'Zurich, Switzerland',
    lat: 47.3769,
    lng: 8.5417,
    regions: ['Europe'],
    scope: 'local',
    countries: 1,
    panels: 70000,
    desc: 'Swiss OOH company. Posters, digital, transport, and railway station advertising across Switzerland.',
    parent: 'APG SGA SA',
    url: 'https://www.apgsga.ch',
    image_url: 'https://images.unsplash.com/photo-1530122037265-a5f1d91d9155?w=800',
  },
  {
    name: 'Big Tree',
    hq: 'Kuala Lumpur, Malaysia',
    lat: 3.139,
    lng: 101.6869,
    regions: ['Asia-Pacific'],
    scope: 'local',
    countries: 1,
    panels: 5000,
    desc: 'Malaysian OOH media owner. Expressway billboards, street furniture, transit, and digital formats.',
    parent: 'Big Tree Outdoor Sdn Bhd',
    url: 'https://www.bigtreebillboard.com',
    image_url: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800',
  },
  {
    name: 'Bangkok Metro Networks',
    hq: 'Bangkok, Thailand',
    lat: 13.7467,
    lng: 100.5384,
    regions: ['Asia-Pacific'],
    scope: 'local',
    countries: 1,
    panels: 3000,
    desc: 'Thailand transit media operator. Advertising and commercial media in Bangkok metro and transit systems.',
    parent: 'Bangkok Metro Networks Limited',
    url: '',
    image_url: 'https://images.unsplash.com/photo-1604357201168-7c8c1c3f5e2a?w=800',
  },
  {
    name: 'Asiaray Media Group',
    hq: 'Hong Kong',
    lat: 22.3193,
    lng: 114.1694,
    regions: ['Asia-Pacific'],
    scope: 'regional',
    countries: 4,
    panels: 15000,
    desc: 'Hong Kong-based OOH media company. Airport, metro, billboard, and transport advertising across Greater China and Southeast Asia.',
    parent: 'Asiaray Media Group Limited',
    url: 'https://www.asiaray.com',
    image_url: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800',
  },
  {
    name: 'Alliance Media',
    hq: 'Johannesburg, South Africa',
    lat: -26.2041,
    lng: 28.0473,
    regions: ['Africa'],
    scope: 'regional',
    countries: 15,
    panels: 28000,
    desc: 'OOH media company operating billboards and airport advertising across multiple African countries.',
    parent: 'Alliance Media',
    url: 'https://www.alliancemedia.com',
    image_url: 'https://images.unsplash.com/photo-1577563908411-5077b6dc7624?w=800',
  },
  {
    name: 'Addd Inc',
    hq: 'Seoul, South Korea',
    lat: 37.5665,
    lng: 126.978,
    regions: ['Asia-Pacific'],
    scope: 'local',
    countries: 1,
    panels: 8000,
    desc: 'South Korean national media owner. OOH and digital advertising formats across Korea.',
    parent: 'Addd Inc',
    url: '',
    image_url: 'https://images.unsplash.com/photo-1538485399081-7c8ed7144b6c?w=800',
  },
  {
    name: 'Bauer Media Outdoor',
    hq: 'London, UK',
    lat: 51.5189,
    lng: -0.0899,
    regions: ['Europe'],
    scope: 'local',
    countries: 1,
    panels: 25000,
    desc: 'UK OOH media owner (formerly Clear Channel UK). Roadside, retail, airport, and digital formats.',
    parent: 'Bauer Media Group',
    url: '',
    image_url: 'https://images.unsplash.com/photo-1495567720989-cebdbdd97913?w=800',
  },
  {
    name: 'Branded Cities',
    hq: 'New York, USA',
    lat: 40.7558,
    lng: -73.987,
    regions: ['North America'],
    scope: 'local',
    countries: 2,
    panels: 1200,
    desc: 'North American premium OOH media company. Large-format, spectacular, and digital displays in major US and Canadian cities.',
    parent: 'Branded Cities Network',
    url: '',
    image_url: 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=800',
  },
  {
    name: 'blowUP media',
    hq: 'Cologne, Germany',
    lat: 50.94,
    lng: 6.95,
    regions: ['Europe'],
    scope: 'regional',
    countries: 8,
    panels: 3000,
    desc: 'European large-format OOH specialist. Giant posters, banners, murals, and building wraps across major European cities.',
    parent: 'Ströer Group',
    url: 'https://www.blowupmedia.com',
    image_url: 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f?w=800',
  },
  {
    name: 'Val Morgan Outdoor',
    hq: 'Sydney, Australia',
    lat: -33.865,
    lng: 151.2099,
    regions: ['Asia-Pacific'],
    scope: 'local',
    countries: 1,
    panels: 9000,
    desc: "Australia's cinema and OOH advertising network. Cinema screens, shopping centre, and airport formats.",
    parent: 'Val Morgan Cinema / Hoyts Group',
    url: 'https://www.valmorganoutdoor.com.au',
    image_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
  },
  {
    name: 'Broadsign',
    hq: 'Montreal, Canada',
    lat: 45.5017,
    lng: -73.5673,
    regions: ['Worldwide'],
    scope: 'global',
    countries: 0,
    panels: 0,
    desc: 'OOH software and programmatic platform for media owners, agencies, and advertisers worldwide. Not a structure owner — provides the digital infrastructure layer.',
    parent: 'Broadsign International, LLC',
    url: 'https://www.broadsign.com',
    image_url: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800',
  },
];

// Quick-select chips for the report form — the biggest global operators
export const TOP_OOH_OPERATORS = [
  'JCDecaux',
  'Clear Channel Outdoor',
  'Plan B Media',
  'Lamar Advertising',
  'OUTFRONT Media',
  'Ströer',
  'oOh!media',
  'Ocean Outdoor',
  'Focus Media',
  'Pattison Outdoor',
];

// Full list for datalist suggestions
export const ALL_OOH_OPERATORS = OOH_MEDIA_CORPS.map((c) => c.name).sort();
