import {
  Bike,
  BookOpen,
  Coins,
  Grid3x3,
  Music,
  Smartphone,
  FileText,
  Box,
  Ruler,
  Activity,
  Image as ImageIcon,
  Layers,
  Watch,
  ScanLine,
  SprayCan,
} from 'lucide-react';

// ── Lab project registry ─────────────────────────────────────────────────────
// Single source of truth for code-defined Lab projects (pages that live in the
// codebase rather than only as LabPrototype rows).
//
// To add a new Lab project:
//   1. create the page in src/pages,
//   2. add its <Route> in App.jsx,
//   3. add one entry below.
//
// From there it is automatic:
//   • the Hub (/lab) surfaces it, and
//   • the Control Console (/lab/admin) auto-provisions a LabPrototype record for
//     it on load — so every new project appears in the control panel with no
//     manual database step, and stays fully togglable (access / status / visible).
export const LAB_PROJECTS = [
  {
    path: '/lab/coin',
    title: 'Genesis Chip',
    icon: Coins,
    desc: 'The crypto chip you can hold — physical artifact, 64mm Ø, 1:1 on-chain twin.',
    access: 'restricted',
    status: 'live',
    sort_order: 0,
  },
  {
    path: '/lab/token',
    title: 'Genesis Token',
    icon: Layers,
    desc: '$OOHEX fungible token — community currency, rewards, governance, burn.',
    access: 'restricted',
    status: 'live',
    sort_order: 1,
  },
  {
    path: '/lab/coin-poster',
    title: 'Genesis Coin Poster',
    icon: Coins,
    desc: 'Concept art — three faces, I Ching wheel, action-verb edge, the set.',
    access: 'restricted',
    status: 'live',
    sort_order: 2,
  },
  {
    path: '/lab/poster',
    title: 'Hex Engine Poster',
    icon: ImageIcon,
    desc: 'Concept art — the 3D Ba Gua sphere, mechanics of the hand, 64 states.',
    access: 'restricted',
    status: 'live',
    sort_order: 3,
  },
  {
    path: '/lab/sequencer',
    title: 'I Ching Sequencer',
    icon: Music,
    desc: '64-step sequencer across King Wen, Fuxi & protocol orderings.',
    access: 'restricted',
    status: 'live',
    sort_order: 4,
  },
  {
    path: '/lab/simulator',
    title: 'Hex Engine Simulator',
    icon: Grid3x3,
    desc: 'Working 64-state device — rings, Ba Gua dial, BLE frame log.',
    access: 'restricted',
    status: 'in_build',
    sort_order: 5,
  },
  {
    path: '/lab/nft',
    title: 'NFT Creator',
    icon: ImageIcon,
    desc: '3D subvertising card studio — slab casing, grading labels, artwork mint.',
    access: 'restricted',
    status: 'live',
    sort_order: 6,
  },
  {
    path: '/lab/device',
    title: '3D Device',
    icon: Box,
    desc: 'Interactive brass coin-cube — six rotating faces, spin, explode, HUD.',
    access: 'restricted',
    status: 'live',
    sort_order: 7,
  },
  {
    path: '/lab/livingcoin',
    title: 'Living Coin',
    icon: Ruler,
    desc: 'Coin-cube production spec — technical drawings, six rotating brass faces.',
    access: 'restricted',
    status: 'in_build',
    sort_order: 8,
  },
  {
    path: '/lab/companion',
    title: 'Phone Companion',
    icon: Smartphone,
    desc: 'Five mobile screens: pair, map, hex, wallet, DAO.',
    access: 'restricted',
    status: 'in_build',
    sort_order: 9,
  },
  {
    path: '/lab/devices',
    title: 'Devices',
    icon: Watch,
    desc: 'Wearables & desktop apps — OOH Watch, NFC field tag, desktop console.',
    access: 'restricted',
    status: 'in_build',
    sort_order: 10,
  },
  {
    path: '/lab/spec',
    title: 'Engineering Spec',
    icon: FileText,
    desc: 'State machine, BLE GATT, frame format, screen inventory.',
    access: 'restricted',
    status: 'in_build',
    sort_order: 11,
  },
  {
    path: '/lab/status',
    title: 'Status Report',
    icon: Activity,
    desc: 'Lab engineering log — build register, revisions, pipeline, roadmap.',
    access: 'restricted',
    status: 'live',
    sort_order: 12,
  },
  {
    path: '/lab/book',
    title: 'The Guild · Book',
    icon: BookOpen,
    desc: 'Subvertising & Brandalism — the field manual as a working-draft reader. Chapters 1–3 open for review.',
    access: 'restricted',
    status: 'live',
    sort_order: 13,
  },
  {
    path: '/lab/streetrunner',
    title: 'Streetrunner',
    icon: Bike,
    desc: 'OE-1K/66 — Akira-class field-bike concept. Vector → blueprint → 3D concept art.',
    access: 'restricted',
    status: 'live',
    sort_order: 14,
  },
  {
    path: '/lab/scanner',
    title: 'Ad Scanner',
    icon: ScanLine,
    desc: 'Advertising detection camera — point, shoot, identify brands/logos/branding on any surface and catalog the hit.',
    access: 'public',
    status: 'live',
    sort_order: 15,
  },
  {
    path: '/lab/graffiti-cam',
    title: 'Graffiti Camera',
    icon: SprayCan,
    desc: 'Field camera for graffiti and street art — point, shoot, classify medium/style, and log to the graffiti portal and field map.',
    access: 'public',
    status: 'live',
    sort_order: 16,
  },
];

export const LAB_BY_PATH = Object.fromEntries(LAB_PROJECTS.map((p) => [p.path, p]));
