// Curated open-access field footage on subvertising, adbusting, brandalism,
// billboard liberation & culture jamming. All videos hosted on YouTube.
const thumb = (id) => `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;

export const PROGRAMS = [
  {
    id: "zunPa9rGndg",
    title: "Subvertisers for London",
    channel: "Dog Section Press",
    topic: "Subvertising",
    runtime: "21:00",
    deck: "A street-level documentary following the crews who replace city ads with art across the capital after dark.",
  },
  {
    id: "PLKqDw8DF6E",
    title: "History & Tactics of the Adbusting Movement",
    channel: "Michelle Tylicki",
    topic: "Adbusting",
    runtime: "Talk",
    deck: "A primer on the half-century of tactical media resistance — from early detournement to the modern billboard raid.",
  },
  {
    id: "lKRmVwqhEdE",
    title: "Brandalism 2014 — 40 Artists, 10 Cities, 365 Takeovers",
    channel: "Brandalism",
    topic: "Brandalism",
    runtime: "Doc",
    deck: "The largest coordinated subvertising action ever staged — a year of unsanctioned ad-space reclamation across Europe.",
  },
  {
    id: "K4WnZAUOIxI",
    title: "Brandalism 2015 — COP21 Paris",
    channel: "Brandalism",
    topic: "Climate",
    runtime: "Doc",
    deck: "600 bus-shelter takeovers detonated during the Paris climate summit to expose fossil-fuel greenwashing.",
  },
  {
    id: "KjgrHX94bKo",
    title: "Billboard Liberation Front",
    channel: "Negativland · Sonic Outlaws",
    topic: "Billboard Liberation",
    runtime: "Short",
    deck: "The original San Francisco outfit that taught a generation how to improve advertising with a ladder and a pun.",
  },
  {
    id: "FR76Iqh1a1A",
    title: "Ad Busters — Culture Jamming",
    channel: "Shakyegg",
    topic: "Culture Jamming",
    runtime: "Doc",
    deck: "The Vancouver manifesto that sparked the global culture-jamming movement and put a meme in every shopping mall.",
  },
  {
    id: "d7HOLcrFMHE",
    title: "Culture Jamming — by The Media Foundation",
    channel: "Adbusters",
    topic: "Culture Jamming",
    runtime: "Short",
    deck: "A short from the foundation itself — on détournement, mental environment, and the right to a clean signscape.",
  },
  {
    id: "WWaNV2gGhuU",
    title: "Subvertising — Rocketboom",
    channel: "Rocketboom",
    topic: "Subvertising",
    runtime: "Short",
    deck: "A bite-size field report from the early web-broadcast era on the craft and politics of ad replacement.",
  },
].map((p) => ({ ...p, thumb: thumb(p.id) }));